### PR TITLE
Added DependsOn dependencies to resolvers

### PR DESCRIPTION
**Pull request by cliffordduke**
Added DependsOn schema and source to resolvers in order to prevent race condition as it will reference non-existent resources.

### CODE REVIEW

**Comment by lucasschejtman** [comment]
Hi @cliffordduke, I was in the middle of a merge and now your branch has conflicts. I was going to add the dependsOn but I'll let get it from your PR if you pull latest.

**Comment by cliffordduke** [comment]
Hi @lucasschejtman, I see you've merged it already, were the conflicts resolved?

**Comment by lucasschejtman** [comment]
Yep, I resolved and merged your branch. Thanks!

**Comment by cliffordduke** [comment]
No problem! thanks for resolving it!

**Pull request merged**
